# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-ExCtags
version:      0.02
version_from: lib/Parse/ExCtags.pm
installdirs:  site
requires:
    IO::All:                       0
    Spiffy:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
